export const SITE_CONFIG = {
    name: "Samuel Wu",
    role: "Builder · Founder · AI Automation Engineer",
    location: "Boulder, Colorado",
    description: "I build and ship revenue-generating software, AI automations, and high-performance websites. I optimize for speed, clarity, and outcomes.",
    email: "samuel@example.com",
    socials: {
        github: "https://github.com",
        twitter: "https://twitter.com",
        linkedin: "https://linkedin.com",
    },
    nav: [
        { label: "Projects", href: "/projects" },
        { label: "About", href: "/about" },
        { label: "Contact", href: "/contact" },
    ],
    projectCategories: [
        { id: "all", label: "All Projects", slug: "" },
        { id: "apps", label: "Apps", slug: "apps" },
        { id: "websites", label: "Websites", slug: "websites" },
        { id: "games", label: "Games", slug: "games" },
        { id: "tools", label: "Tools", slug: "tools" },
    ],
    projects: [
        {
            title: "HOA Reply AI",
            description: "AI system that automates HOA inboxes and reduces admin load by 85%.",
            problem: "HOA managers were drowning in repetitive questions.",
            outcome: "Reduced response time from 24h to <5m.",
            tags: ["AI Agent", "Next.js", "Automation"],
            href: "/work/hoa-reply",
            featured: true,
            category: "apps",
        },
        {
            title: "Certirise",
            description: "Compliance SaaS for recurring license renewals with automated tracking.",
            problem: "Manual spreadsheets led to missed renewals and fines.",
            outcome: "Zero missed renewals across 50+ clients.",
            tags: ["SaaS", "Compliance", "Stripe"],
            href: "/work/certirise",
            featured: true,
            category: "apps",
        },
        {
            title: "Avelae",
            description: "E-commerce brand focused on product testing and fulfillment.",
            problem: "Existing 3PLs were too slow for rapid product testing.",
            outcome: "Custom fulfillment workflow integrated with Shopify.",
            tags: ["E-commerce", "Operations", "Shopify"],
            href: "/work/avelae",
            featured: true,
            category: "websites",
        },
        {
            title: "Clivora",
            description: "Video repurposing and content automation tool.",
            problem: "Creating shorts from long-form video was manual and slow.",
            outcome: "Automated clipping and captioning pipeline.",
            tags: ["Video AI", "FFmpeg", "Cloud Functions"],
            href: "/work/clivora",
            featured: true,
            category: "tools",
        },
        {
            title: "Memory Game",
            description: "A classic memory card matching game built with React and TypeScript.",
            problem: "Need for a fun, interactive memory training game.",
            outcome: "Engaging game with scoring system and difficulty levels.",
            tags: ["React", "TypeScript", "Game"],
            href: "/games/memory",
            featured: true,
            category: "games",
        },
        {
            title: "Snake Game",
            description: "A modern take on the classic Snake game with smooth animations.",
            problem: "Creating an enjoyable retro-style game experience.",
            outcome: "Smooth gameplay with responsive controls and high scores.",
            tags: ["JavaScript", "Canvas", "Game"],
            href: "/games/snake",
            featured: true,
            category: "games",
        },
        {
            title: "Reaction Game",
            description: "Test your reaction time with this fast-paced clicking game.",
            problem: "Need for a simple, engaging reaction time test.",
            outcome: "Fun game that tracks and displays reaction times.",
            tags: ["React", "JavaScript", "Game"],
            href: "/games/reaction",
            featured: true,
            category: "games",
        },
    ],
};
