export const SITE_CONFIG = {
    name: "Samuel Wu",
    role: "Builder · Founder · AI Automation Engineer",
    location: "Boulder, Colorado",
    description: "I build stuff that makes money. AI automations, SaaS products, and websites that actually work. Fast, clear, results-focused.",
    email: "samuel@example.com",
    socials: {
        github: "https://github.com",
        twitter: "https://twitter.com",
        linkedin: "https://linkedin.com",
    },
    nav: [
        { label: "Projects", href: "/projects" },
        { label: "About", href: "/about" },
        { label: "Contact", href: "/contact" },
    ],
    personalProjects: [
        {
            title: "Game Project 1",
            description: "A fun game built with [tech stack]. Features include [key features].",
            tags: ["Game", "Unity", "C#"],
            href: "#",
            category: "game",
        },
        {
            title: "Mobile App",
            description: "iOS/Android app that solves [problem]. Built with React Native.",
            tags: ["Mobile", "React Native", "iOS"],
            href: "#",
            category: "app",
        },
        {
            title: "Web App",
            description: "Interactive web application with [features]. Built with modern web tech.",
            tags: ["Web", "React", "TypeScript"],
            href: "#",
            category: "web",
        },
    ],
    otherInterests: [
        {
            title: "Piano",
            description: "Classical piano performances and recordings.",
            href: "/piano",
            icon: "🎹",
        },
    ],
    projects: [
        {
            title: "HOA Reply AI",
            description: "AI system that automates HOA inboxes and reduces admin load by 85%.",
            problem: "HOA managers were drowning in repetitive questions.",
            outcome: "Reduced response time from 24h to <5m.",
            tags: ["AI Agent", "Next.js", "Automation"],
            href: "/work/hoa-reply",
            featured: true,
        },
        {
            title: "Certirise",
            description: "Compliance SaaS for recurring license renewals with automated tracking.",
            problem: "Manual spreadsheets led to missed renewals and fines.",
            outcome: "Zero missed renewals across 50+ clients.",
            tags: ["SaaS", "Compliance", "Stripe"],
            href: "/work/certirise",
            featured: true,
        },
        {
            title: "Avelae",
            description: "E-commerce brand focused on product testing and fulfillment.",
            problem: "Existing 3PLs were too slow for rapid product testing.",
            outcome: "Custom fulfillment workflow integrated with Shopify.",
            tags: ["E-commerce", "Operations", "Shopify"],
            href: "/work/avelae",
            featured: true,
        },
        {
            title: "Clivora",
            description: "Video repurposing and content automation tool.",
            problem: "Creating shorts from long-form video was manual and slow.",
            outcome: "Automated clipping and captioning pipeline.",
            tags: ["Video AI", "FFmpeg", "Cloud Functions"],
            href: "/work/clivora",
            featured: true,
        },
    ],
};
